// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/echo/v1/echo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadShape int32

const (
	PayloadShape_PAYLOAD_SHAPE_UNSPECIFIED     PayloadShape = 0
	PayloadShape_PAYLOAD_SHAPE_STRING          PayloadShape = 1
	PayloadShape_PAYLOAD_SHAPE_BYTES           PayloadShape = 2
	PayloadShape_PAYLOAD_SHAPE_EMBEDDING_FLOAT PayloadShape = 3
	PayloadShape_PAYLOAD_SHAPE_EMBEDDING_BYTES PayloadShape = 4
	PayloadShape_PAYLOAD_SHAPE_MIXED           PayloadShape = 5
)

// Enum value maps for PayloadShape.
var (
	PayloadShape_name = map[int32]string{
		0: "PAYLOAD_SHAPE_UNSPECIFIED",
		1: "PAYLOAD_SHAPE_STRING",
		2: "PAYLOAD_SHAPE_BYTES",
		3: "PAYLOAD_SHAPE_EMBEDDING_FLOAT",
		4: "PAYLOAD_SHAPE_EMBEDDING_BYTES",
		5: "PAYLOAD_SHAPE_MIXED",
	}
	PayloadShape_value = map[string]int32{
		"PAYLOAD_SHAPE_UNSPECIFIED":     0,
		"PAYLOAD_SHAPE_STRING":          1,
		"PAYLOAD_SHAPE_BYTES":           2,
		"PAYLOAD_SHAPE_EMBEDDING_FLOAT": 3,
		"PAYLOAD_SHAPE_EMBEDDING_BYTES": 4,
		"PAYLOAD_SHAPE_MIXED":           5,
	}
)

func (x PayloadShape) Enum() *PayloadShape {
	p := new(PayloadShape)
	*p = x
	return p
}

func (x PayloadShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadShape) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_echo_v1_echo_proto_enumTypes[0].Descriptor()
}

func (PayloadShape) Type() protoreflect.EnumType {
	return &file_pkg_echo_v1_echo_proto_enumTypes[0]
}

func (x PayloadShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadShape.Descriptor instead.
func (PayloadShape) EnumDescriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

type EchoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Shape PayloadShape           `protobuf:"varint,2,opt,name=shape,proto3,enum=pkg.echo.v1.PayloadShape" json:"shape,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EchoRequest_StringPayload
	//	*EchoRequest_BytesPayload
	//	*EchoRequest_EmbeddingFloat
	//	*EchoRequest_EmbeddingBytes
	//	*EchoRequest_Mixed
	Payload       isEchoRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EchoRequest) GetShape() PayloadShape {
	if x != nil {
		return x.Shape
	}
	return PayloadShape_PAYLOAD_SHAPE_UNSPECIFIED
}

func (x *EchoRequest) GetPayload() isEchoRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoRequest) GetStringPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*EchoRequest_StringPayload); ok {
			return x.StringPayload
		}
	}
	return ""
}

func (x *EchoRequest) GetBytesPayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EchoRequest_BytesPayload); ok {
			return x.BytesPayload
		}
	}
	return nil
}

func (x *EchoRequest) GetEmbeddingFloat() *EmbeddingFloat {
	if x != nil {
		if x, ok := x.Payload.(*EchoRequest_EmbeddingFloat); ok {
			return x.EmbeddingFloat
		}
	}
	return nil
}

func (x *EchoRequest) GetEmbeddingBytes() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EchoRequest_EmbeddingBytes); ok {
			return x.EmbeddingBytes
		}
	}
	return nil
}

func (x *EchoRequest) GetMixed() *MixedPayload {
	if x != nil {
		if x, ok := x.Payload.(*EchoRequest_Mixed); ok {
			return x.Mixed
		}
	}
	return nil
}

type isEchoRequest_Payload interface {
	isEchoRequest_Payload()
}

type EchoRequest_StringPayload struct {
	StringPayload string `protobuf:"bytes,10,opt,name=string_payload,json=stringPayload,proto3,oneof"`
}

type EchoRequest_BytesPayload struct {
	BytesPayload []byte `protobuf:"bytes,11,opt,name=bytes_payload,json=bytesPayload,proto3,oneof"`
}

type EchoRequest_EmbeddingFloat struct {
	EmbeddingFloat *EmbeddingFloat `protobuf:"bytes,12,opt,name=embedding_float,json=embeddingFloat,proto3,oneof"`
}

type EchoRequest_EmbeddingBytes struct {
	EmbeddingBytes []byte `protobuf:"bytes,13,opt,name=embedding_bytes,json=embeddingBytes,proto3,oneof"`
}

type EchoRequest_Mixed struct {
	Mixed *MixedPayload `protobuf:"bytes,14,opt,name=mixed,proto3,oneof"`
}

func (*EchoRequest_StringPayload) isEchoRequest_Payload() {}

func (*EchoRequest_BytesPayload) isEchoRequest_Payload() {}

func (*EchoRequest_EmbeddingFloat) isEchoRequest_Payload() {}

func (*EchoRequest_EmbeddingBytes) isEchoRequest_Payload() {}

func (*EchoRequest_Mixed) isEchoRequest_Payload() {}

type EchoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Query              string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Kubernetes         *KubernetesInfo        `protobuf:"bytes,2,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Request            *RequestInfo           `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Runtime            *RuntimeInfo           `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Extensions         []*ExtendedInfo        `protobuf:"bytes,5,rep,name=extensions,proto3" json:"extensions,omitempty"`
	ServerDurationNs   int64                  `protobuf:"varint,6,opt,name=server_duration_ns,json=serverDurationNs,proto3" json:"server_duration_ns,omitempty"`
	ReceivedAtUnixNano int64                  `protobuf:"varint,7,opt,name=received_at_unix_nano,json=receivedAtUnixNano,proto3" json:"received_at_unix_nano,omitempty"`
	SentAtUnixNano     int64                  `protobuf:"varint,8,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	Shape              PayloadShape           `protobuf:"varint,9,opt,name=shape,proto3,enum=pkg.echo.v1.PayloadShape" json:"shape,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EchoResponse_StringPayload
	//	*EchoResponse_BytesPayload
	//	*EchoResponse_EmbeddingFloat
	//	*EchoResponse_EmbeddingBytes
	//	*EchoResponse_Mixed
	Payload       isEchoResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *EchoResponse) GetKubernetes() *KubernetesInfo {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *EchoResponse) GetRequest() *RequestInfo {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EchoResponse) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *EchoResponse) GetExtensions() []*ExtendedInfo {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *EchoResponse) GetServerDurationNs() int64 {
	if x != nil {
		return x.ServerDurationNs
	}
	return 0
}

func (x *EchoResponse) GetReceivedAtUnixNano() int64 {
	if x != nil {
		return x.ReceivedAtUnixNano
	}
	return 0
}

func (x *EchoResponse) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *EchoResponse) GetShape() PayloadShape {
	if x != nil {
		return x.Shape
	}
	return PayloadShape_PAYLOAD_SHAPE_UNSPECIFIED
}

func (x *EchoResponse) GetPayload() isEchoResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoResponse) GetStringPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*EchoResponse_StringPayload); ok {
			return x.StringPayload
		}
	}
	return ""
}

func (x *EchoResponse) GetBytesPayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EchoResponse_BytesPayload); ok {
			return x.BytesPayload
		}
	}
	return nil
}

func (x *EchoResponse) GetEmbeddingFloat() *EmbeddingFloat {
	if x != nil {
		if x, ok := x.Payload.(*EchoResponse_EmbeddingFloat); ok {
			return x.EmbeddingFloat
		}
	}
	return nil
}

func (x *EchoResponse) GetEmbeddingBytes() []byte {
	if x != nil {
		if x, ok := x.Payload.(*EchoResponse_EmbeddingBytes); ok {
			return x.EmbeddingBytes
		}
	}
	return nil
}

func (x *EchoResponse) GetMixed() *MixedPayload {
	if x != nil {
		if x, ok := x.Payload.(*EchoResponse_Mixed); ok {
			return x.Mixed
		}
	}
	return nil
}

type isEchoResponse_Payload interface {
	isEchoResponse_Payload()
}

type EchoResponse_StringPayload struct {
	StringPayload string `protobuf:"bytes,10,opt,name=string_payload,json=stringPayload,proto3,oneof"`
}

type EchoResponse_BytesPayload struct {
	BytesPayload []byte `protobuf:"bytes,11,opt,name=bytes_payload,json=bytesPayload,proto3,oneof"`
}

type EchoResponse_EmbeddingFloat struct {
	EmbeddingFloat *EmbeddingFloat `protobuf:"bytes,12,opt,name=embedding_float,json=embeddingFloat,proto3,oneof"`
}

type EchoResponse_EmbeddingBytes struct {
	EmbeddingBytes []byte `protobuf:"bytes,13,opt,name=embedding_bytes,json=embeddingBytes,proto3,oneof"`
}

type EchoResponse_Mixed struct {
	Mixed *MixedPayload `protobuf:"bytes,14,opt,name=mixed,proto3,oneof"`
}

func (*EchoResponse_StringPayload) isEchoResponse_Payload() {}

func (*EchoResponse_BytesPayload) isEchoResponse_Payload() {}

func (*EchoResponse_EmbeddingFloat) isEchoResponse_Payload() {}

func (*EchoResponse_EmbeddingBytes) isEchoResponse_Payload() {}

func (*EchoResponse_Mixed) isEchoResponse_Payload() {}

type ExtendedInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Info          *KeyMultivalue         `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendedInfo) Reset() {
	*x = ExtendedInfo{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedInfo) ProtoMessage() {}

func (x *ExtendedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedInfo.ProtoReflect.Descriptor instead.
func (*ExtendedInfo) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendedInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtendedInfo) GetInfo() *KeyMultivalue {
	if x != nil {
		return x.Info
	}
	return nil
}

type KubernetesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodNode       string                 `protobuf:"bytes,4,opt,name=pod_node,json=podNode,proto3" json:"pod_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesInfo) Reset() {
	*x = KubernetesInfo{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesInfo) ProtoMessage() {}

func (x *KubernetesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesInfo.ProtoReflect.Descriptor instead.
func (*KubernetesInfo) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *KubernetesInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *KubernetesInfo) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *KubernetesInfo) GetPodNode() string {
	if x != nil {
		return x.PodNode
	}
	return ""
}

type RequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	ParsedUrl     *ParsedURL             `protobuf:"bytes,5,opt,name=parsed_url,json=parsedUrl,proto3" json:"parsed_url,omitempty"`
	Header        []*KeyMultivalue       `protobuf:"bytes,6,rep,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{4}
}

func (x *RequestInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RequestInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *RequestInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RequestInfo) GetParsedUrl() *ParsedURL {
	if x != nil {
		return x.ParsedUrl
	}
	return nil
}

func (x *RequestInfo) GetHeader() []*KeyMultivalue {
	if x != nil {
		return x.Header
	}
	return nil
}

type ParsedURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RawPath       string                 `protobuf:"bytes,4,opt,name=raw_path,json=rawPath,proto3" json:"raw_path,omitempty"`
	RawQuery      string                 `protobuf:"bytes,5,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Query         []*KeyMultivalue       `protobuf:"bytes,6,rep,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedURL) Reset() {
	*x = ParsedURL{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedURL) ProtoMessage() {}

func (x *ParsedURL) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedURL.ProtoReflect.Descriptor instead.
func (*ParsedURL) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{5}
}

func (x *ParsedURL) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ParsedURL) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ParsedURL) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ParsedURL) GetRawPath() string {
	if x != nil {
		return x.RawPath
	}
	return ""
}

func (x *ParsedURL) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *ParsedURL) GetQuery() []*KeyMultivalue {
	if x != nil {
		return x.Query
	}
	return nil
}

type KeyMultivalue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMultivalue) Reset() {
	*x = KeyMultivalue{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMultivalue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMultivalue) ProtoMessage() {}

func (x *KeyMultivalue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMultivalue.ProtoReflect.Descriptor instead.
func (*KeyMultivalue) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{6}
}

func (x *KeyMultivalue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyMultivalue) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoVersion     string                 `protobuf:"bytes,1,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	GoArch        string                 `protobuf:"bytes,2,opt,name=go_arch,json=goArch,proto3" json:"go_arch,omitempty"`
	GoOs          string                 `protobuf:"bytes,3,opt,name=go_os,json=goOs,proto3" json:"go_os,omitempty"`
	NumCpus       int64                  `protobuf:"varint,4,opt,name=num_cpus,json=numCpus,proto3" json:"num_cpus,omitempty"`
	NumGoroutines int64                  `protobuf:"varint,5,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	MainModule    string                 `protobuf:"bytes,6,opt,name=main_module,json=mainModule,proto3" json:"main_module,omitempty"`
	MainPath      string                 `protobuf:"bytes,7,opt,name=main_path,json=mainPath,proto3" json:"main_path,omitempty"`
	MainVersion   string                 `protobuf:"bytes,8,opt,name=main_version,json=mainVersion,proto3" json:"main_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *RuntimeInfo) GetGoArch() string {
	if x != nil {
		return x.GoArch
	}
	return ""
}

func (x *RuntimeInfo) GetGoOs() string {
	if x != nil {
		return x.GoOs
	}
	return ""
}

func (x *RuntimeInfo) GetNumCpus() int64 {
	if x != nil {
		return x.NumCpus
	}
	return 0
}

func (x *RuntimeInfo) GetNumGoroutines() int64 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *RuntimeInfo) GetMainModule() string {
	if x != nil {
		return x.MainModule
	}
	return ""
}

func (x *RuntimeInfo) GetMainPath() string {
	if x != nil {
		return x.MainPath
	}
	return ""
}

func (x *RuntimeInfo) GetMainVersion() string {
	if x != nil {
		return x.MainVersion
	}
	return ""
}

type EmbeddingFloat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingFloat) Reset() {
	*x = EmbeddingFloat{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingFloat) ProtoMessage() {}

func (x *EmbeddingFloat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingFloat.ProtoReflect.Descriptor instead.
func (*EmbeddingFloat) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{8}
}

func (x *EmbeddingFloat) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type MixedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Ratio         float64                `protobuf:"fixed64,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers       []int32                `protobuf:"varint,7,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Blob          []byte                 `protobuf:"bytes,9,opt,name=blob,proto3" json:"blob,omitempty"`
	Extra         *KeyMultivalue         `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixedPayload) Reset() {
	*x = MixedPayload{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixedPayload) ProtoMessage() {}

func (x *MixedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixedPayload.ProtoReflect.Descriptor instead.
func (*MixedPayload) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{9}
}

func (x *MixedPayload) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MixedPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MixedPayload) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MixedPayload) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *MixedPayload) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MixedPayload) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MixedPayload) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *MixedPayload) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *MixedPayload) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *MixedPayload) GetExtra() *KeyMultivalue {
	if x != nil {
		return x.Extra
	}
	return nil
}

// StatusRequest determines the error (if any) to return to the caller, representing
// on-wire status that the caller expects from the server.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// force_grpc_status forces a status response conforming to the standard
	// gRPC Core status codes: https://grpc.github.io/grpc/core/md_doc_statuscodes.html
	// Following those standard status codes, a value of zero (or unset) will
	// return OK.
	ForceGrpcStatus uint32 `protobuf:"varint,1,opt,name=force_grpc_status,json=forceGrpcStatus,proto3" json:"force_grpc_status,omitempty"`
	// message is an optional string returned alongside the code.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetForceGrpcStatus() uint32 {
	if x != nil {
		return x.ForceGrpcStatus
	}
	return 0
}

func (x *StatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatusResponse is a (currently) empty gRPC message.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_echo_v1_echo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_echo_v1_echo_proto_rawDescGZIP(), []int{11}
}

var File_pkg_echo_v1_echo_proto protoreflect.FileDescriptor

const file_pkg_echo_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/echo/v1/echo.proto\x12\vpkg.echo.v1\"\xd5\x02\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12/\n" +
	"\x05shape\x18\x02 \x01(\x0e2\x19.pkg.echo.v1.PayloadShapeR\x05shape\x12'\n" +
	"\x0estring_payload\x18\n" +
	" \x01(\tH\x00R\rstringPayload\x12%\n" +
	"\rbytes_payload\x18\v \x01(\fH\x00R\fbytesPayload\x12F\n" +
	"\x0fembedding_float\x18\f \x01(\v2\x1b.pkg.echo.v1.EmbeddingFloatH\x00R\x0eembeddingFloat\x12)\n" +
	"\x0fembedding_bytes\x18\r \x01(\fH\x00R\x0eembeddingBytes\x121\n" +
	"\x05mixed\x18\x0e \x01(\v2\x19.pkg.echo.v1.MixedPayloadH\x00R\x05mixedB\t\n" +
	"\apayload\"\xc2\x05\n" +
	"\fEchoResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12;\n" +
	"\n" +
	"kubernetes\x18\x02 \x01(\v2\x1b.pkg.echo.v1.KubernetesInfoR\n" +
	"kubernetes\x122\n" +
	"\arequest\x18\x03 \x01(\v2\x18.pkg.echo.v1.RequestInfoR\arequest\x122\n" +
	"\aruntime\x18\x04 \x01(\v2\x18.pkg.echo.v1.RuntimeInfoR\aruntime\x129\n" +
	"\n" +
	"extensions\x18\x05 \x03(\v2\x19.pkg.echo.v1.ExtendedInfoR\n" +
	"extensions\x12,\n" +
	"\x12server_duration_ns\x18\x06 \x01(\x03R\x10serverDurationNs\x121\n" +
	"\x15received_at_unix_nano\x18\a \x01(\x03R\x12receivedAtUnixNano\x12)\n" +
	"\x11sent_at_unix_nano\x18\b \x01(\x03R\x0esentAtUnixNano\x12/\n" +
	"\x05shape\x18\t \x01(\x0e2\x19.pkg.echo.v1.PayloadShapeR\x05shape\x12'\n" +
	"\x0estring_payload\x18\n" +
	" \x01(\tH\x00R\rstringPayload\x12%\n" +
	"\rbytes_payload\x18\v \x01(\fH\x00R\fbytesPayload\x12F\n" +
	"\x0fembedding_float\x18\f \x01(\v2\x1b.pkg.echo.v1.EmbeddingFloatH\x00R\x0eembeddingFloat\x12)\n" +
	"\x0fembedding_bytes\x18\r \x01(\fH\x00R\x0eembeddingBytes\x121\n" +
	"\x05mixed\x18\x0e \x01(\v2\x19.pkg.echo.v1.MixedPayloadH\x00R\x05mixedB\t\n" +
	"\apayload\"R\n" +
	"\fExtendedInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04info\x18\x02 \x01(\v2\x1a.pkg.echo.v1.KeyMultivalueR\x04info\"\x87\x01\n" +
	"\x0eKubernetesInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_node\x18\x04 \x01(\tR\apodNode\"\xdf\x01\n" +
	"\vRequestInfo\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x125\n" +
	"\n" +
	"parsed_url\x18\x05 \x01(\v2\x16.pkg.echo.v1.ParsedURLR\tparsedUrl\x122\n" +
	"\x06header\x18\x06 \x03(\v2\x1a.pkg.echo.v1.KeyMultivalueR\x06header\"\xb5\x01\n" +
	"\tParsedURL\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x19\n" +
	"\braw_path\x18\x04 \x01(\tR\arawPath\x12\x1b\n" +
	"\traw_query\x18\x05 \x01(\tR\brawQuery\x120\n" +
	"\x05query\x18\x06 \x03(\v2\x1a.pkg.echo.v1.KeyMultivalueR\x05query\"9\n" +
	"\rKeyMultivalue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xfd\x01\n" +
	"\vRuntimeInfo\x12\x1d\n" +
	"\n" +
	"go_version\x18\x01 \x01(\tR\tgoVersion\x12\x17\n" +
	"\ago_arch\x18\x02 \x01(\tR\x06goArch\x12\x13\n" +
	"\x05go_os\x18\x03 \x01(\tR\x04goOs\x12\x19\n" +
	"\bnum_cpus\x18\x04 \x01(\x03R\anumCpus\x12%\n" +
	"\x0enum_goroutines\x18\x05 \x01(\x03R\rnumGoroutines\x12\x1f\n" +
	"\vmain_module\x18\x06 \x01(\tR\n" +
	"mainModule\x12\x1b\n" +
	"\tmain_path\x18\a \x01(\tR\bmainPath\x12!\n" +
	"\fmain_version\x18\b \x01(\tR\vmainVersion\"(\n" +
	"\x0eEmbeddingFloat\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xe2\x02\n" +
	"\fMixedPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05ratio\x18\x04 \x01(\x01R\x05ratio\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x18\n" +
	"\anumbers\x18\a \x03(\x05R\anumbers\x12:\n" +
	"\x05attrs\x18\b \x03(\v2$.pkg.echo.v1.MixedPayload.AttrsEntryR\x05attrs\x12\x12\n" +
	"\x04blob\x18\t \x01(\fR\x04blob\x120\n" +
	"\x05extra\x18\n" +
	" \x01(\v2\x1a.pkg.echo.v1.KeyMultivalueR\x05extra\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\rStatusRequest\x12*\n" +
	"\x11force_grpc_status\x18\x01 \x01(\rR\x0fforceGrpcStatus\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eStatusResponse*\xbf\x01\n" +
	"\fPayloadShape\x12\x1d\n" +
	"\x19PAYLOAD_SHAPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PAYLOAD_SHAPE_STRING\x10\x01\x12\x17\n" +
	"\x13PAYLOAD_SHAPE_BYTES\x10\x02\x12!\n" +
	"\x1dPAYLOAD_SHAPE_EMBEDDING_FLOAT\x10\x03\x12!\n" +
	"\x1dPAYLOAD_SHAPE_EMBEDDING_BYTES\x10\x04\x12\x17\n" +
	"\x13PAYLOAD_SHAPE_MIXED\x10\x052\x8c\x01\n" +
	"\x06Echoer\x12=\n" +
	"\x04Echo\x12\x18.pkg.echo.v1.EchoRequest\x1a\x19.pkg.echo.v1.EchoResponse\"\x00\x12C\n" +
	"\x06Status\x12\x1a.pkg.echo.v1.StatusRequest\x1a\x1b.pkg.echo.v1.StatusResponse\"\x00B'Z%github.com/ripta/netdebug/pkg/echo/v1b\x06proto3"

var (
	file_pkg_echo_v1_echo_proto_rawDescOnce sync.Once
	file_pkg_echo_v1_echo_proto_rawDescData []byte
)

func file_pkg_echo_v1_echo_proto_rawDescGZIP() []byte {
	file_pkg_echo_v1_echo_proto_rawDescOnce.Do(func() {
		file_pkg_echo_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_echo_v1_echo_proto_rawDesc), len(file_pkg_echo_v1_echo_proto_rawDesc)))
	})
	return file_pkg_echo_v1_echo_proto_rawDescData
}

var file_pkg_echo_v1_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_echo_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_echo_v1_echo_proto_goTypes = []any{
	(PayloadShape)(0),      // 0: pkg.echo.v1.PayloadShape
	(*EchoRequest)(nil),    // 1: pkg.echo.v1.EchoRequest
	(*EchoResponse)(nil),   // 2: pkg.echo.v1.EchoResponse
	(*ExtendedInfo)(nil),   // 3: pkg.echo.v1.ExtendedInfo
	(*KubernetesInfo)(nil), // 4: pkg.echo.v1.KubernetesInfo
	(*RequestInfo)(nil),    // 5: pkg.echo.v1.RequestInfo
	(*ParsedURL)(nil),      // 6: pkg.echo.v1.ParsedURL
	(*KeyMultivalue)(nil),  // 7: pkg.echo.v1.KeyMultivalue
	(*RuntimeInfo)(nil),    // 8: pkg.echo.v1.RuntimeInfo
	(*EmbeddingFloat)(nil), // 9: pkg.echo.v1.EmbeddingFloat
	(*MixedPayload)(nil),   // 10: pkg.echo.v1.MixedPayload
	(*StatusRequest)(nil),  // 11: pkg.echo.v1.StatusRequest
	(*StatusResponse)(nil), // 12: pkg.echo.v1.StatusResponse
	nil,                    // 13: pkg.echo.v1.MixedPayload.AttrsEntry
}
var file_pkg_echo_v1_echo_proto_depIdxs = []int32{
	0,  // 0: pkg.echo.v1.EchoRequest.shape:type_name -> pkg.echo.v1.PayloadShape
	9,  // 1: pkg.echo.v1.EchoRequest.embedding_float:type_name -> pkg.echo.v1.EmbeddingFloat
	10, // 2: pkg.echo.v1.EchoRequest.mixed:type_name -> pkg.echo.v1.MixedPayload
	4,  // 3: pkg.echo.v1.EchoResponse.kubernetes:type_name -> pkg.echo.v1.KubernetesInfo
	5,  // 4: pkg.echo.v1.EchoResponse.request:type_name -> pkg.echo.v1.RequestInfo
	8,  // 5: pkg.echo.v1.EchoResponse.runtime:type_name -> pkg.echo.v1.RuntimeInfo
	3,  // 6: pkg.echo.v1.EchoResponse.extensions:type_name -> pkg.echo.v1.ExtendedInfo
	0,  // 7: pkg.echo.v1.EchoResponse.shape:type_name -> pkg.echo.v1.PayloadShape
	9,  // 8: pkg.echo.v1.EchoResponse.embedding_float:type_name -> pkg.echo.v1.EmbeddingFloat
	10, // 9: pkg.echo.v1.EchoResponse.mixed:type_name -> pkg.echo.v1.MixedPayload
	7,  // 10: pkg.echo.v1.ExtendedInfo.info:type_name -> pkg.echo.v1.KeyMultivalue
	6,  // 11: pkg.echo.v1.RequestInfo.parsed_url:type_name -> pkg.echo.v1.ParsedURL
	7,  // 12: pkg.echo.v1.RequestInfo.header:type_name -> pkg.echo.v1.KeyMultivalue
	7,  // 13: pkg.echo.v1.ParsedURL.query:type_name -> pkg.echo.v1.KeyMultivalue
	13, // 14: pkg.echo.v1.MixedPayload.attrs:type_name -> pkg.echo.v1.MixedPayload.AttrsEntry
	7,  // 15: pkg.echo.v1.MixedPayload.extra:type_name -> pkg.echo.v1.KeyMultivalue
	1,  // 16: pkg.echo.v1.Echoer.Echo:input_type -> pkg.echo.v1.EchoRequest
	11, // 17: pkg.echo.v1.Echoer.Status:input_type -> pkg.echo.v1.StatusRequest
	2,  // 18: pkg.echo.v1.Echoer.Echo:output_type -> pkg.echo.v1.EchoResponse
	12, // 19: pkg.echo.v1.Echoer.Status:output_type -> pkg.echo.v1.StatusResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_echo_v1_echo_proto_init() }
func file_pkg_echo_v1_echo_proto_init() {
	if File_pkg_echo_v1_echo_proto != nil {
		return
	}
	file_pkg_echo_v1_echo_proto_msgTypes[0].OneofWrappers = []any{
		(*EchoRequest_StringPayload)(nil),
		(*EchoRequest_BytesPayload)(nil),
		(*EchoRequest_EmbeddingFloat)(nil),
		(*EchoRequest_EmbeddingBytes)(nil),
		(*EchoRequest_Mixed)(nil),
	}
	file_pkg_echo_v1_echo_proto_msgTypes[1].OneofWrappers = []any{
		(*EchoResponse_StringPayload)(nil),
		(*EchoResponse_BytesPayload)(nil),
		(*EchoResponse_EmbeddingFloat)(nil),
		(*EchoResponse_EmbeddingBytes)(nil),
		(*EchoResponse_Mixed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_echo_v1_echo_proto_rawDesc), len(file_pkg_echo_v1_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_echo_v1_echo_proto_goTypes,
		DependencyIndexes: file_pkg_echo_v1_echo_proto_depIdxs,
		EnumInfos:         file_pkg_echo_v1_echo_proto_enumTypes,
		MessageInfos:      file_pkg_echo_v1_echo_proto_msgTypes,
	}.Build()
	File_pkg_echo_v1_echo_proto = out.File
	file_pkg_echo_v1_echo_proto_goTypes = nil
	file_pkg_echo_v1_echo_proto_depIdxs = nil
}
